plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    implementation("dev.kosmx.player-anim:player-animation-lib-forge:${project.player_anim_version}")
    compileOnly("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}") {transitive false}//using common causes complaints

    // Better Mob Combat Dependencies
    implementation("maven.modrinth:better-combat:${project.better_combat_version}-neoforge")


    // Mod Compatibility
    compileOnly("maven.modrinth:entity-model-features:${project.emf_version}-neoforge-1.21")
    compileOnly("maven.modrinth:entitytexturefeatures:${project.etf_version}-neoforge-1.21")
    implementation("maven.modrinth:minecraft-comes-alive-reborn:${project.mcar_version}")

}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'
artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.forEach {
        commonResources it
    }
}